### ISSUE TITLE
When padding & number parameters too large, the accuracy of the numbers is lost!

### ISSUE THREAD

**Issue by starzou** [mikecao/hashkit#2]
```javascript
const Hashkit = require('hashkit');

let hashkit = new Hashkit({
  shuffle: true,
  mask: true,
  padding: 8
});

console.log(hashkit);

let bigNumber = 100000000000;
let str = hashkit.encode(bigNumber);

console.log(str, hashkit.decode(str));
```

> Hashkit {
>   options: 
>    { chars: 'WLgvI6CN7tqi8xfdFJZYDVeuP5K0kpAhmTEG2SjH39cXoyMzQbsraUBwl1OR4n',
>      shuffle: true,
>      mask: true,
>      padding: 8,
>      seed: 123456789 } }
> ef6lrEuqQMa 100000006000

**Comment by mikecao** [comment]
In Javascript the `Number.MAX_SAFE_INTEGER` value is 9007199254740991. Precision will be lost if you go outside that range. So you should try to keep your base number and padding within that value.

**Comment by starzou** [comment]
Thank you for your reply.

Is it possible to add a minLength parameter to ensure that the generated hash is long enough?

Example:

``` javascript
const hashkit = new Hashkit({
  shuffle: true,
  mask: true,
  minLength: 6
});

hashkit.encode(1); // --> abcdef
hashkit.encode(2); // --> abcdeg
hashkit.encode(3); // --> abcdeh
```

**Comment by mikecao** [comment]
I don't think you can assure length because the mask is random. With a mask of 3, the value can be as low as 100 and high as 999, which will produce different results.

But you can just test several values until you find one that is suitable for you.

**Comment by starzou** [comment]
Do you know this project?  https://github.com/ivanakimov/hashids.js

I think using minLength instead of padding would be better.

The getMaskedNum method is not a good implementation, It will make the result inconsistent.

**Comment by mikecao** [comment]
You shouldn't rely on the padding to determine length. The padding is supposed to be random. Your input number needs a minimum value if you want to ensure length.

The default character set is 62 characters, meaning it's base 62. Then `Math.pow(base, length - 1)` will give you the minimum value you need to pass in for a given length. So if you want minimum length 4, you have to pass in `Math.pow(62, 3)` which is `238328`.

**Comment by starzou** [comment]
I got it. Thanks so much.
